title: vanquish religion become robot
author: Lord yuval Slijper
theme: minima
email: your-email@domain.com
description: religion bad, robot good.
              join my efforts to better humankind and live forever.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
